### ISSUE TITLE
pass-by-value explanation misleading

### ISSUE THREAD

**Issue by senocular** [nas5w/typeofnan-javascript-quizzes#10]
https://github.com/nas5w/typeofnan-javascript-quizzes/blob/master/content/questions/pass-by-value/index.md

> However, changing the value of a primitive data type such as string (or number, or boolean) does not change the original variable

The kind of value is irrelevant here.  Primitive or object, the behavior would be the same.  

```
let b1 = ['Lisa prefers Johnny']; // now an object
let b2 = b1;
b2 = ['Lisa prefers Mark']; // still does not change b1
console.log(b1); // ['Lisa prefers Johnny'];
```

Instead, the difference is changing the property of an object vs. changing the value of a variable.  Changing the property of an object will be seen through other references to that object.  Changing the value of a variable does not affect other variables or object properties (with the exception of parameter variables being reflected in the `arguments` object, but we're going to pretend that's not a thing).

**Comment by nas5w** [comment]
Thanks @senocular (btw, I recognize your handle from the learnjavascript sub!). Would you be willing to do a PR to clarify the explanation?

**Comment by senocular** [comment]
@nas5w I think it might depend on what you want to do for #11 .  It sounds like you don't want to change pass-by-value question but just change the title? If so then a replacement explanation can be done now.  But if there's any change to the question itself (such as passing the values through a function before mutating thereby validating the current title) that could affect what the new explanation says.

And yeah, that was me 😉

**Comment by nas5w** [comment]
Yeah, for #11 I' thinking we just correct the title / explanation.
