### ISSUE TITLE
Merge object-prop-mutation and pass-by-value

### ISSUE THREAD

**Issue by senocular** [nas5w/typeofnan-javascript-quizzes#11]
https://github.com/nas5w/typeofnan-javascript-quizzes/blob/master/content/questions/object-prop-mutation/index.md

https://github.com/nas5w/typeofnan-javascript-quizzes/blob/master/content/questions/pass-by-value/index.md

object-prop-mutation is a subset of what pass-by-value is testing while pass-by-value is improperly named (there's no actual passing happening).

You can replace object-prop-mutation's content with that in pass-by-value to beef it up.  Then you can get rid of pass-by-value or change it to use functions to get some actual passing going on, but there still might be some redundancy between the two (using functions might provide enough separation to not be as noticeable).

**Comment by nas5w** [comment]
I don't mind having redundancy. I'd rather just fix up the pass-by-value title and leave object-prop-mutation alone.

**Comment by nas5w** [comment]
Closing this as the redundancy is fine. The pass-by-value explanation has been clarified.
