### ISSUE TITLE
Add README instructions for running the app locally

### ISSUE THREAD

**Issue by nas5w** [nas5w/typeofnan-javascript-quizzes#16]
The `README` does not specify how to run the application locally. This would be helpful as contributors would be able to verify their proposed question(s) or functionality changes work as expected. Ideally, this section would have the following content:

- How to clone the repo
- How to install dependencies (using yarn)
  - How to install yarn globally if they don't have yarn yet
- How to start the app and view it

**Comment by advename** [comment]
Ill take it :)

**Comment by nas5w** [comment]
@advename all yours, thanks!

**Comment by advename** [comment]
You got your PR :)

**Comment by nas5w** [comment]
Closed in PR #18
