### ISSUE TITLE
Make README prettier

### ISSUE THREAD

**Issue by nas5w** [nas5w/typeofnan-javascript-quizzes#22]
Hoping someone out there has experience making attractive README files for open source projects. Open to suggestions of things like emojis, badges, new sections, whatever helps make the project more attractive to both use as an app and contribute to.

**Comment by pragapraga** [comment]
I will try this one @nas5w

**Comment by nas5w** [comment]
Cool! Try to take some inspiration from other popular repos if possible, @pragapraga. Thanks!

**Comment by nas5w** [comment]
Thanks @pragapraga for your contribution!

Still keeping this PR open if anyone else has ideas!

**Comment by NicholasG04** [comment]
Hiya, I've made some contributions in #27 for this issue!

**Comment by designeranna1** [comment]
Added option to save offline in  Readme.md . Please have a look.
