### ISSUE TITLE
Add a question generator

### ISSUE THREAD

**Issue by nas5w** [nas5w/typeofnan-javascript-quizzes#26]
Anyone up for adding a node-based question generator? Essentially, this should be a node command that you can run, preferably something like:

`node new-question queston-route`

This should generate a new folder called `question-route` within the `content/questions` folder, and generate an `index.md` file with a reasonable question markdown template.

**Comment by peakercope** [comment]
hi
I can help with this one

**Comment by nas5w** [comment]
@peakercope awesome! Looking forward to seeing what you come up with.

**Comment by peakercope** [comment]
Please, look at https://github.com/nas5w/typeofnan-javascript-quizzes/pull/45

**Comment by nas5w** [comment]
@peakercope This is amazing!

Would you mind adding instructions to the readme in the Contributing section?

Also, one thing that'd be really helpful is if the question generator could automatically add the `order` number to the question frontmatter. The order number is simply the count of all questions (folders) in the `questions` directory. 

Alternatively, we can get this merged in and create another issue to try to get the `order` number pre-populating.

Thank you!

**Comment by peakercope** [comment]
what is `order` field used for?
I'm trying to understand how we can manage it if two different contributors create new question at same time. so we will have two different questions with identical `order` value.

**Comment by nas5w** [comment]
That is just the sort order of the returned data, so collisions aren't a big deal. I'm not sure how else sort order should be determined.

**Comment by peakercope** [comment]
done
