### ISSUE TITLE
string-methods answer is incorrect

### ISSUE THREAD

**Issue by senocular** [nas5w/typeofnan-javascript-quizzes#57]
**Describe the bug**

Answer specified in [string-methods](https://github.com/nas5w/typeofnan-javascript-quizzes/blob/master/content/questions/string-methods/index.md) is incorrect. The correct answer is marked as "search" but should be "indexOf".  [search](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search) finds the index of a regular expression, not a string (if a string is given, it will be converted to a regex).  When finding a string you would use [indexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf).

**To Reproduce**
1. Go to https://quiz.typeofnan.dev/string-methods/
2. Click on indexOf
2. Click on Submit

**Expected behavior**
Answer is correct.

**Comment by nas5w** [comment]
Whoops, I merged a fix before you could do yours. I actually removed `search` altogether because it coincidentally does work in this scenario. Maybe it's worth a separate question emphasizing the difference between the two?

**Comment by senocular** [comment]
@nas5w That works too :)
