### ISSUE TITLE
Incorrect description of Curly-q

### ISSUE THREAD

**Issue by Hooked74** [nas5w/typeofnan-javascript-quizzes#66]
The Curly-q question has the following chunk of code:
```js
const foo = () => {
  return {
    foo: "foo";
  }
}
```
This code example will result in a syntax error due to **;** inside the object.
It is proposed to choose from the following [options](http://joxi.ru/n2YZxxGFb4V8qA) but in fact, not one of them is suitable.

Either add a new answer (syntax error) or correct the description:
```js
const foo = () => {
  return {
    foo: "foo"
  };
}
```

The same errors are in the [Explanation](http://joxi.ru/8AnpqqZhzX0dWm) section.

**Comment by nas5w** [comment]
Thank you for catching this! Can you do a PR to fix it? Would really appreciate it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
