### ISSUE TITLE
poor UI for the clear answer dialogue

### ISSUE THREAD

**Issue by Batey96** [nas5w/typeofnan-javascript-quizzes#86]
a windows dialog pops up when the clear my Answer buton is clicked.This is a probably not the best  UI/UX. as shown below.
**Screenshots**
If applicable, add screenshots to help explain your problem

![Oct 16 2019 4_34 PM](https://user-images.githubusercontent.com/24868289/66935716-654cac00-f034-11e9-9a02-2f1f193dc761.gif)

a better and possible way is to modalise this feature as shown.
![Oct 16 2019 4_38 PM](https://user-images.githubusercontent.com/24868289/66935855-aba20b00-f034-11e9-9c39-1dabcb924601.gif)

@nas5w can i be assigned to this issue
.

**Comment by nas5w** [comment]
Looks good! I tend to use alert since it's accessible. Please verify your modal is accessible!`
