### ISSUE TITLE
fix:No UI wait indicator for a fetch of external resource

### ISSUE THREAD

**Issue by Batey96** [nas5w/typeofnan-javascript-quizzes#87]
**Describe the bug**

When a fetch for an external resource like GitHub contributors is done,there is nothing to inform the user about the operation if there is a slow of bandwidth or any other delay.The assigned dom element to display the result of this fetch becomes blank even after the delayed fetch.

**Expected behavior**
an indicator should be put in placed to inform users of pending operation

**Screenshots**
![Oct 16 2019 5_14 PM](https://user-images.githubusercontent.com/24868289/66938166-a3e46580-f038-11e9-8d63-5f876c1ef125.gif)

@nas5w can i be assigned this

**Comment by nas5w** [comment]
Sure, thanks!
